import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    domains: [
      "quierocasa.cl",
      "cf.bstatic.com",
      "encrypted-tbn0.gstatic.com",
      "example.com",
      "cdn-icons-png.flaticon.com",
      "res.cloudinary.com",
      "hips.hearstapps.com",
      "hips.hearstapps.com",
      "www.construyehogar.com",
      "www.casasparaconstruir.com",
      "images.homify.com",
      "hips.hearstapps.com",
      "www.construyehogar.com",
      "www.casasparaconstruir.com",
      "images.homify.com",
      "d219336yigegi3.cloudfront.net/",
"hips.hearstapps.com",
"forandes.com",
"woodpecker.com.co",
"media.admagazine.com",
"www.revistaaxxis.com.co",
"inmobiliariaviventi.co",
"images.adsttc.com",
"pics.nuroa.com",
"decofilia.com",
"cf.bstatic.com",
"nucleosdemadera.com",
"encrypted-tbn0.gstatic.com",
"www.cucutanuestra.com",
"hips.hearstapps.com",
"images.homify.com",
"www.casasparaconstruir.com",
"www.construyehogar.com",
"madera-sostenible.com",
"encrypted-tbn0.gstatic.com",
"construcasasprefabricados.com.co",
"cache.enlaceinmobiliario.cl",
"images.ctfassets.net",
"www.insidehome.com.co",
"micasaconstructora.com",
"www.centralcasas.cl",
"photos.encuentra24.com",
"prefabrihouse.com.co",
"i.blogs.es",
"media1.amarilo.com.co",
"www.torcaldeantequera.com",
"construcasasprefabricados.com.co",
"images.ctfassets.net",

    ],
  },
  /* config options here */
};

export default nextConfig;
